// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDsGOvOxAnRIxk9mqelIE9KZLKEv1-xsyA',
    appId: '1:303937407237:web:63f2edef61f872e4c2cf6c',
    messagingSenderId: '303937407237',
    projectId: 'nexus-now',
    authDomain: 'nexus-now.firebaseapp.com',
    storageBucket: 'nexus-now.appspot.com',
    measurementId: 'G-CLXL39LE79',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC7_lRzubgN1J4gN3Si5YVJ6paVWtlwneI',
    appId: '1:303937407237:android:d71f1d3284f57c6dc2cf6c',
    messagingSenderId: '303937407237',
    projectId: 'nexus-now',
    storageBucket: 'nexus-now.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA18ccZqJ_G-b58Io2LuuUlk9B5Ob6BcNw',
    appId: '1:303937407237:ios:5aa7e8cfd3286b3fc2cf6c',
    messagingSenderId: '303937407237',
    projectId: 'nexus-now',
    storageBucket: 'nexus-now.appspot.com',
    iosBundleId: 'com.example.nexusNow',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA18ccZqJ_G-b58Io2LuuUlk9B5Ob6BcNw',
    appId: '1:303937407237:ios:5aa7e8cfd3286b3fc2cf6c',
    messagingSenderId: '303937407237',
    projectId: 'nexus-now',
    storageBucket: 'nexus-now.appspot.com',
    iosBundleId: 'com.example.nexusNow',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDsGOvOxAnRIxk9mqelIE9KZLKEv1-xsyA',
    appId: '1:303937407237:web:2de17813f13ea063c2cf6c',
    messagingSenderId: '303937407237',
    projectId: 'nexus-now',
    authDomain: 'nexus-now.firebaseapp.com',
    storageBucket: 'nexus-now.appspot.com',
    measurementId: 'G-L9MTGZW2FY',
  );
}
